# Generated by scripts/build_homebrew.py; regenerate after changes.
class Lime < Formula
  include Language::Python::Virtualenv

  desc 'Markdown for Ghostty with large headings and native scroll and search'
  url 'file:///Users/spencerdixon/Rails/lime/dist/lime-0.1.0.tar.gz'
  version '0.1.0'
  sha256 'fe9d12c8fa15413eb52a1b6e1cb62848b4e880eda78678922112cc23214e0bf0'
  license 'MIT'

  depends_on 'python@3.14'
  depends_on 'pillow'

  resource 'mdurl' do
    url 'https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl'
    sha256 '84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8'
  end

  resource 'markdown-it-py' do
    url 'https://files.pythonhosted.org/packages/b3/81/4da04ced5a082363ecfa159c010d200ecbd959ae410c10c0264a38cac0f5/markdown_it_py-4.2.0-py3-none-any.whl'
    sha256 '9f7ebbcd14fe59494226453aed97c1070d83f8d24b6fc3a3bcf9a38092641c4a'
  end

  resource 'pygments' do
    url 'https://files.pythonhosted.org/packages/71/46/17f022dd3e953bf20a04a028a21ec746d942f8d2af30fa0f124fa0e6a684/pygments-2.21.0-py3-none-any.whl'
    sha256 '2363c69b61c4a97c838da3b130dcd6468f4848992b21a82f2a63ec34377137d9'
  end

  resource 'rich' do
    url 'https://files.pythonhosted.org/packages/b3/76/6d163cfac87b632216f71879e6b2cf17163f773ff59c00b5ff4900a80fa3/rich-14.3.4-py3-none-any.whl'
    sha256 '07e7adb4690f68864777b1450859253bed81a99a31ac321ac1817b2313558952'
  end

  resource 'ruamel-yaml' do
    url 'https://files.pythonhosted.org/packages/b8/0c/51f6841f1d84f404f92463fc2b1ba0da357ca1e3db6b7fbda26956c3b82a/ruamel_yaml-0.19.1-py3-none-any.whl'
    sha256 '27592957fedf6e0b62f281e96effd28043345e0e66001f97683aa9a40c667c93'
  end

  def install
    venv = virtualenv_create(libexec, 'python3.14')
    venv.pip_install resources
    venv.pip_install_and_link buildpath/'lime_markdown-0.1.0-py3-none-any.whl'
    doc.install 'README.md', 'demo.md', 'diagram.png', 'config.example.yaml'
  end

  test do
    (testpath/'sample.md').write <<~MARKDOWN
      # Hello from lime

      | Name | Value |
      | --- | --- |
      | lime | 42 |

      ```python
      print('works')
      ```
    MARKDOWN
    output = shell_output("#{bin}/lime --plain #{testpath}/sample.md")
    assert_match 'Hello from lime', output
    assert_match '42', output
    assert_match "print('works')", output
    refute_match "\e", output
    system libexec/'bin/python', '-c', 'from PIL import ImageFont; import lime'
  end
end
