"""Build a release archive and a formula with checksummed, locked resources.

Without --url, the formula uses the local archive, suitable for testing before
publishing. With --url and --homepage, it is ready to put in a public tap.
"""

import argparse
import hashlib
import subprocess
import tarfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def ruby_string(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", help="public HTTPS URL of the archive you will upload")
    parser.add_argument("--homepage", help="project's public HTTPS homepage")
    args = parser.parse_args()
    if bool(args.url) != bool(args.homepage):
        parser.error("--url and --homepage must be supplied together")
    if args.url and not all(value.startswith("https://") for value in (args.url, args.homepage)):
        parser.error("release URLs must use HTTPS")
    project = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    version = project["version"]
    subprocess.run(["uv", "build", "--wheel"], cwd=ROOT, check=True)
    wheel = ROOT / "dist" / f"lime_markdown-{version}-py3-none-any.whl"
    archive = ROOT / "dist" / f"lime-{version}.tar.gz"
    with tarfile.open(archive, "w:gz") as bundle:
        for path in [
            wheel,
            ROOT / "README.md",
            ROOT / "LICENSE",
            ROOT / "examples" / "demo.md",
            ROOT / "config.example.yaml",
            ROOT / "examples" / "diagram.png",
        ]:
            bundle.add(path, arcname=f"lime-{version}/{path.name}")

    lock = tomllib.loads((ROOT / "uv.lock").read_text())
    # Pillow is supplied by Homebrew so the formula works on macOS and Linux
    # without vendoring an architecture-specific extension or compiling it here.
    packages = {package["name"]: package for package in lock["package"]}
    resource_blocks = []
    for name in ("mdurl", "markdown-it-py", "pygments", "rich", "ruamel-yaml"):
        package = packages[name]
        wheel_resource = next(item for item in package["wheels"] if "-none-any.whl" in item["url"])
        resource_blocks.append(
            f"  resource {ruby_string(name)} do\n"
            f"    url {ruby_string(wheel_resource['url'])}\n"
            f"    sha256 {ruby_string(wheel_resource['hash'].removeprefix('sha256:'))}\n"
            "  end\n"
        )
    formula = (
        "# Generated by scripts/build_homebrew.py; regenerate after changes.\n"
        "class Lime < Formula\n"
        "  include Language::Python::Virtualenv\n\n"
        "  desc 'Markdown for Ghostty with large headings and native scroll and search'\n"
    )
    if args.homepage:
        formula += f"  homepage {ruby_string(args.homepage)}\n"
    formula += (
        f"  url {ruby_string(args.url or archive.as_uri())}\n"
        f"  version {ruby_string(version)}\n"
        f"  sha256 '{hashlib.sha256(archive.read_bytes()).hexdigest()}'\n"
        "  license 'MIT'\n\n"
        "  depends_on 'python@3.14'\n"
        "  depends_on 'pillow'\n\n" + "\n".join(resource_blocks) + "\n  def install\n"
        "    venv = virtualenv_create(libexec, 'python3.14')\n"
        "    venv.pip_install resources\n"
        f"    venv.pip_install_and_link buildpath/{ruby_string(wheel.name)}\n"
        "    doc.install 'README.md', 'demo.md', 'diagram.png', 'config.example.yaml'\n"
        "  end\n\n"
        "  test do\n"
        "    (testpath/'sample.md').write <<~MARKDOWN\n"
        "      # Hello from lime\n\n"
        "      | Name | Value |\n"
        "      | --- | --- |\n"
        "      | lime | 42 |\n\n"
        "      ```python\n"
        "      print('works')\n"
        "      ```\n"
        "    MARKDOWN\n"
        '    output = shell_output("#{bin}/lime #{testpath}/sample.md")\n'
        "    assert_match 'Hello from lime', output\n"
        "    assert_match '42', output\n"
        "    assert_match \"print('works')\", output\n"
        '    refute_match "\\e", output\n'
        "    system libexec/'bin/python', '-c', 'from PIL import ImageFont; import lime'\n"
        "  end\n"
        "end\n"
    )
    destination = ROOT / "Formula" / "lime.rb"
    destination.parent.mkdir(exist_ok=True)
    destination.write_text(formula)
    print(f"Built {archive}\nWrote {destination}")


if __name__ == "__main__":
    main()
